spring.application.name=stock-manager

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/stock_manager}
spring.datasource.username=${DB_USERNAME:bluedot}
spring.datasource.password=${DB_PASSWORD:bluedot1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.expiration=900000
jwt.secret=RNFI9aP73c+Hau983hLjNWTZXPiVzx8BAC5cv8wpFIg=

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n

# TODO solo dejar en desarrollo para ver los logs con el correlation-id
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
